config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :users
  end

  resources :questions do
    collection do
      get :pending_questions
    end
    post :approval
    resources :answers
  end

  resources :comments, only: [:edit, :create, :update, :destroy]

  get '/upvote' => 'vote#upvote'
  get '/downvote' => 'vote#downvote'
  get '/accepted' => 'vote#accepted'

  resources :profiles, only: [:show, :edit, :update]

  get '/pages/tags' => 'pages#tags'
  get '/pages/rules' => 'pages#rules'
  get '/users' => 'pages#users'
  get 'search' => 'search#search', :as => 'search'

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  root 'questions#index'
  get '/all_tags' => 'home#all_tags'

  resources :home do
    collection do
      post :local_switcher
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :upvotes, as: :upvotable
  has_many :downvotes, as: :downvotable
  has_many :comments, as: :commentable

  before_destroy :check_if_answer_present

  acts_as_taggable_on :tags
  include Impressionist::IsImpressionable
  is_impressionable

  searchable :auto_index => true, :auto_remove => true do
    text :title, :stored => true
    text :description, :stored => true
    string :tag_list, :multiple => true, :stored => true
  end

  scope :approved_questions, -> {
    where(:approved => true)
  }
  scope :unapproved_questions, -> {
    where(:approved => false)
  }

  private

  def check_if_answer_present
    if self.answers.count > 0
      errors.add(:base, 'This question cannot be deleted because answers exist.')
      return false
    end
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: [:destroy, :approval]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_question, only: [:edit, :update, :destroy]

  impressionist :actions=>[:show], unique: [:session_hash]

  layout 'member'
  # GET /questions
  # GET /questions.json
  def index
    if params[:t].present?
      @questions =  Question.includes(:answers, :user => :profile).order('updated_at DESC').approved_questions.tagged_with(params[:t])
    else
      @questions = Question.includes(:answers, :user => :profile).order('updated_at DESC').approved_questions
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.includes(:answers, :user => :profile).find(params[:id])
    if @question.approved || moderator?
      @no_of_view = @question.impressionist_count
      @comments = @question.comments.includes(:user => :profile)
    else
      redirect_to root_path
    end
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
    if @question.user != current_user
      redirect_to questions_path
    end
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created and waiting for approval.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pending_questions
    if moderator? || admin?
      @questions = Question.includes(:answers, :user => :profile).order('updated_at DESC').unapproved_questions
    else
      redirect_to root_path
    end
  end

  def approval
    @question = Question.find(params[:question_id])
    if moderator? || admin?
      @question.update_column(:approved, @question.approved ? false : true)
      redirect_to :back
    else
      redirect_to root_path
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :description, :tag_list)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def user_can_give_answer(question)
    return false if !current_user.present?
    answer = Answer.where(:user_id => current_user.id, :question_id => question.id)
    return current_user.present? && !answer.present?
  end

  def top_questions(ques_id)
    Question.approved_questions.includes(:upvotes).where.not(id: ques_id).map{|q| [q.impressionist_count, q.upvotes.count, q.title, q.id]}.sort.first(5)
  end

  def related_questions(question)
    Question.approved_questions.where.not(id: question.id).tagged_with(question.tag_list, :any => true)
  end

  def pending_questions
    Question.unapproved_questions
  end

end

app/views/questions/_answers.html.erb
<div class="row">
  <div class="col-md-12">
    <hr>
    <div class="qanswers-count">
      <h2><%= answers.count %> answers</h2>
    </div>
    <hr>
  </div>
</div>

<% if answers.count > 0 %>
    <% answers.each do |answer| %>
        <div class="each_answers" id="answer_<%= answer.id %>">
          <div class="row">
            <div class="col-md-1 avote-operations">
              <%= render :partial => 'shared/avotes', locals: {answer: answer} %>
            </div>
            <div class="col-md-11">
              <div class="ibox">
                <div class="ibox-content">

                  <%= answer.description.html_safe %>

                  <div class="row">
                    <div class="col-md-8">
                      <div class="vote-info q-user-interactions">
                        <% if current_user == answer.user %>
                            <i class="fa fa-pencil-square"></i> <%= link_to 'Edit', edit_question_answer_path(answer.question, answer), remote: true %>
                            <i class="fa fa-trash"></i> <%= link_to 'Destroy', question_answer_path(answer.question, answer), method: :delete, remote: true %>
                        <% end %>
                        <i class="fa fa-clock-o"></i> <%= distance_of_time_in_words(Time.now, answer.created_at) %>
                        <i class="fa fa-eraser"></i> <%= distance_of_time_in_words(Time.now, answer.updated_at) %>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="small">
                        <div class="social-avatar">
                          <a class="pull-left" href="<%= profile_path(answer.user.profile) %>">
                            <%= image_tag answer.user.profile.photo.present? ? answer.user.profile.photo_url(:thumb) : 'http://placehold.it/50x50' %>
                          </a>

                          <div class="media-body">
                            <a href="<%= profile_path(answer.user.profile) %>">
                              <%= answer.user.profile.name %>
                            </a>
                            <small class="text-muted"><%= answer.user.profile.points %> Points</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div id="answer_<%= answer.id %>-all-comments">
                <%= render :partial => 'comments/comments', locals: {comments: all_comments(answer), commentable: answer} %>
              </div>

            </div>
          </div>
        </div>
    <% end %>
<% end %>

<% if user_can_give_answer(@question) %>
    <div class="new-answer-form">
      <%= render :partial => 'answers/form', locals: {question: @question, answer: Answer.new} %>
    </div>
<% end %>

app/views/questions/_form.html.erb
<%= tinymce_assets %>

<div class="row">
  <div class="col-md-9">
    <div class="ibox float-e-margins">
      <div class="ibox-title">
        <h5><%= @question.new_record? ? 'New Question' : 'Edit Question' %>
          <small><%= @question.new_record? ? 'Create a new' : 'Edit your' %> question</small>
        </h5>
        <div class="ibox-tools">
          <a class="collapse-link">
            <i class="fa fa-chevron-up"></i>
          </a>
          <a href="form_basic.html#" data-toggle="dropdown" class="dropdown-toggle">
            <i class="fa fa-wrench"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <% unless @question.new_record? %><li><a href="<%= question_path(@question) %>">Show</a></li><% end %>
            <li><a href="<%= questions_path %>">All questions</a></li>
          </ul>
        </div>
      </div>
      <div class="ibox-content">
        <div class="row">
          <%= form_for(@question, html: {role: "form"}) do |f| %>
              <%= render :partial => 'shared/errors', :locals => {data_model: @question} %>

              <div class="col-sm-12">
                <div class="form-group">
                  <label>Title</label>
                  <%= f.text_field :title, class: "form-control", placeholder: "question title", required: true %>
                </div>

                <div class="form-group">
                  <label>Question Description</label>
                  <%= f.text_area :description, class: "form-control tinymce", placeholder: "Enter Full name", rows: '7' %>
                  <%= tinymce %>
                </div>

                <div class="form-group">
                  <label>Tags</label>
                  <input type="text" name="question[tag_list]" value="<%= @question.tag_list %>" id="question_tag_list"/>
                  <%#= f.text_field :tag_list, class: 'form-control' %>
                </div>

                <div class="actions pull-right">
                  <%= link_to 'Back', @question.new_record? ? questions_path : question_path(@question), class: 'btn btn-sm btn-white m-t-n-xs'  %>
                  <%= link_to 'Save', 'javascript:void(0)', id: "answer-submit-btn", class: "btn btn-sm btn-primary m-t-n-xs" %>
                  <button type="submit" class="hidden hidden-submit-btn"></button>
                </div>

              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <%= render :partial => 'shared/dashboard_sidebar' %>
  </div>
</div>

<script>

  $(document).ready(function(){
      $('#question_tag_list').tagsInput({
          'defaultText':'add tag...',
          'height':'60px',
          'width':'100%',
          'autocomplete_url': '/all_tags.json',
          'autocomplete': {}
      });



      $('#answer-submit-btn').click(function(){
          var content = tinymce.editors[0].getContent();
          if(content.length > 20){
              $('.hidden-submit-btn').click();
          }
          else{
              alert('Question description must be minimum 20 characters')
          }
      })

  })

</script>

app/views/questions/edit.html.erb
<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-9">
    <% @questions.each do |question| %>
        <div class="row">
          <div id="question_<%= question.id %>">
            <div class="col-md-3">
              <table class="table small m-b-xs">
                <tbody>
                <tr>
                  <td>
                    <strong><%= question.upvotes.count %></strong> Upvotes
                  </td>
                  <td>
                    <strong><%= question.downvotes.count %></strong> Downvotes
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong><%= question.comments.count %></strong> Comments
                  </td>
                  <td>
                    <strong><%= question.impressionist_count %></strong> Views
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong><%= question.tags.count %></strong> Tags
                  </td>
                  <td>
                    <strong><%= question.answers.count %></strong> Answers
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="col-md-9">
              <div class="ibox">
                <div class="ibox-content">
                  <a class="btn-link" href="<%= question_path(question) %>" data-no-turbolink>
                    <h2>
                      <%= question.title %>
                    </h2>
                  </a>

                  <%= question.description.html_safe %>

                  <div class="row">
                    <div class="col-md-8">
                      <% question.tag_list.each do |tag| %>
                          <%= link_to tag, questions_path(t: tag), class: 'btn btn-primary btn-xs' %>
                      <% end %>
                      <div class="vote-info q-user-interactions">
                        <i class="fa fa-clock-o"></i> <%= distance_of_time_in_words(Time.now, question.created_at) %>
                        <i class="fa fa-eraser"></i> <%= distance_of_time_in_words(Time.now, question.updated_at) %>
                        <% if current_user && current_user.is_moderator? %>
                        <strong><%= link_to question.approved ? 'Disapprove' : 'Approve', question_approval_path(question), method: 'post' %></strong>
                        <strong><%= link_to 'Delete', question_path(question), method: 'delete' %></strong>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="small">
                        <div class="social-avatar">
                          <a class="pull-left" href="<%= profile_path(question.user.profile) %>">
                            <%= image_tag question.user.profile.photo.present? ? question.user.profile.photo_url(:thumb) : 'http://placehold.it/50x50' %>
                          </a>

                          <div class="media-body">
                            <a href="<%= profile_path(question.user.profile) %>">
                              <%= question.user.profile.name %>
                            </a>
                            <small class="text-muted"><%= question.user.profile.points %> Points</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div class="col-md-3">
    <%= render :partial => 'shared/dashboard_sidebar' %>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/pending_questions.html.erb
<div class="row">
  <div class="col-md-9">
    <% @questions.each do |question| %>
        <div class="row">
          <div id="question_<%= question.id %>">
            <div class="col-md-3">
              <table class="table small m-b-xs">
                <tbody>
                <tr>
                  <td>
                    <strong><%= question.upvotes.count %></strong> Upvotes
                  </td>
                  <td>
                    <strong><%= question.downvotes.count %></strong> Downvotes
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong><%= question.comments.count %></strong> Comments
                  </td>
                  <td>
                    <strong><%= question.impressionist_count %></strong> Views
                  </td>
                </tr>
                <tr>
                  <td>
                    <strong><%= question.tags.count %></strong> Tags
                  </td>
                  <td>
                    <strong><%= question.answers.count %></strong> Answers
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="col-md-9">
              <div class="ibox">
                <div class="ibox-content">
                  <a class="btn-link" href="<%= question_path(question) %>" target="_blank" data-no-turbolink>
                    <h2>
                      <%= question.title %>
                    </h2>
                  </a>

                  <%= question.description.html_safe %>

                  <div class="row">
                    <div class="col-md-8">
                      <% question.tag_list.each do |tag| %>
                          <%= link_to tag, questions_path(t: tag), class: 'btn btn-primary btn-xs' %>
                      <% end %>
                      <div class="vote-info q-user-interactions">
                        <i class="fa fa-clock-o"></i> <%= distance_of_time_in_words(Time.now, question.created_at) %>
                        <i class="fa fa-eraser"></i> <%= distance_of_time_in_words(Time.now, question.updated_at) %>
                        <strong><%= link_to question.approved ? 'Disapprove' : 'Approve', question_approval_path(question), method: 'post' %></strong>
                        <strong><%= link_to 'Delete', question_path(question), method: 'delete' %></strong>
                      </div>
                    </div>
                    <div class="col-md-4">
                      <div class="small">
                        <div class="social-avatar">
                          <a class="pull-left" href="<%= profile_path(question.user.profile) %>">
                            <%= image_tag question.user.profile.photo.present? ? question.user.profile.photo_url(:thumb) : 'http://placehold.it/50x50' %>
                          </a>

                          <div class="media-body">
                            <a href="<%= profile_path(question.user.profile) %>">
                              <%= question.user.profile.name %>
                            </a>
                            <small class="text-muted"><%= question.user.profile.points %> Points</small>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <div class="col-md-3">
    <%= render :partial => 'shared/dashboard_sidebar' %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="row" id="qid_<%= @question.id %>">
  <div class="col-md-1 qvote-operations">
    <%= render :partial => 'shared/qvotes', locals: {question: @question} %>
  </div>
  <div class="col-md-8">
    <div class="ibox">
      <div class="ibox-content">
        <a class="btn-link" href="javascript:void(0)">
          <h2>
            <%= @question.title %>
          </h2>
        </a>

        <%= @question.description.html_safe %>

        <div class="row">
          <div class="col-md-8">
            <h5>Tags:</h5>
            <% @question.tag_list.each do |tag| %>
                <%= link_to tag, questions_path(t: tag), class: 'btn btn-primary btn-xs' %>
            <% end %>
          </div>
          <div class="col-md-4">
            <div class="small">
              <div class="social-avatar">
                <a class="pull-left" href="<%= profile_path(@question.user.profile) %>">
                  <%= image_tag @question.user.profile.photo.present? ? @question.user.profile.photo_url(:thumb) : 'http://placehold.it/50x50' %>
                </a>

                <div class="media-body">
                  <a href="<%= profile_path(@question.user.profile) %>">
                    <%= @question.user.profile.name %>
                  </a>
                  <small class="text-muted"><%= @question.user.profile.points %> Points</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="vote-info q-user-interactions">
      <% if current_user == @question.user %>
          <i class="fa fa-pencil-square"></i> <%= link_to 'Edit', edit_question_path(@question), 'data-no-turbolink' => true %>
          <i class="fa fa-trash"></i> <%= link_to 'Destroy', question_path(@question), method: :delete %>
      <% end %>
    </div>

    <div id="question-all-comments">
      <%= render :partial => 'comments/comments', locals: {comments: @comments, commentable: @question} %>
    </div>

    <div id="question-all-answers">
      <%= render :partial => 'questions/answers', locals: {answers: @question.answers.includes(:user => :profile)} %>
    </div>
  </div>


  <div class="col-md-3">
    <%= render :partial => 'shared/detail_sidebar', locals: {:question => @question} %>
  </div>
</div>

<% unless current_user.present? %>
<script>
    $(document).ready(function(){
      $('.fa-chevron-up').click(function(e){
         alert("You need to sign in");
          return false;
      });
      $('.fa-chevron-down').click(function(e){
          alert("You need to sign in");
          return false;
      });
  })
</script>
<% end %>