config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :users
  end

  resources :questions do
    collection do
      get :pending_questions
    end
    post :approval
    resources :answers
  end

  resources :comments, only: [:edit, :create, :update, :destroy]

  get '/upvote' => 'vote#upvote'
  get '/downvote' => 'vote#downvote'
  get '/accepted' => 'vote#accepted'

  resources :profiles, only: [:show, :edit, :update]

  get '/pages/tags' => 'pages#tags'
  get '/pages/rules' => 'pages#rules'
  get '/users' => 'pages#users'
  get 'search' => 'search#search', :as => 'search'

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  root 'questions#index'
  get '/all_tags' => 'home#all_tags'

  resources :home do
    collection do
      post :local_switcher
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  attr_accessor :q_id, :a_id
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  layout 'member'
  respond_to :js


  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @commentable = find_commentable
    @commentable.comments.create(comment_params)
    @comments = @commentable.comments.order('created_at ASC')
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comment.update(comment_params)
    @commentable = @comment.commentable
    @comments = @commentable.comments.order('created_at ASC')
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @commentable = @comment.commentable
    @comments = @commentable.comments.order('created_at ASC')
    @comment.destroy
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:description, :user_id, :q_id, :a_id)
  end

  def find_commentable
    if params[:comment][:a_id].present?
      return Answer.find(params[:comment][:a_id])
    else
      return Question.find(params[:comment][:q_id])
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="social-footer <%= 'hidden' if !current_user.present? %>">

  <% comments.each do |comment| %>
      <div class="social-comment">
        <div class="media-body">
          <a href="<%= profile_path(comment.user.profile) %>">
            <%= comment.user.profile.name %>
          </a>
          <%= comment.description %>
          <br>
          <% if current_user == comment.user %>
              <a class="small" href="<%= edit_comment_path(comment) %>" data-remote="true"><i class="fa fa-pencil"></i>
                Edit</a> -
              <a class="small" href="<%= comment_path(comment) %>" data-method="delete" data-remote="true"><i class="fa fa-trash"></i>
                Destroy</a> -
          <% end %>
          <small class="text-muted"><%= distance_of_time_in_words(Time.now - comment.created_at) %></small>
        </div>
      </div>
  <% end %>

  <% if current_user.present? %>
      <div class="social-comment" id="<%= unique_id_generator(commentable) %>">
        <%= render :partial => 'comments/form', locals: {comment: Comment.new, commentable: commentable} %>
      </div>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for(comment, html: {role: "form"}, remote: true) do |f| %>
    <div class="media-body">
      <% if commentable.is_a?(Question) %>
          <%= f.hidden_field :q_id, value: commentable.id %>
      <% else %>
          <%= f.hidden_field :a_id, value: commentable.id %>
      <% end %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.text_field :description, class: "form-control", placeholder: "Write comment...", required: true, autocomplete: 'off'  %>
    </div>
    <input type="submit"
           style="position: absolute; left: -9999px; width: 1px; height: 1px;"
           tabindex="-1" />
<% end %>

app/views/comments/create.js.erb
<% if @commentable.is_a?(Answer) %>
    var answer_id = <%= @commentable.id %>;
    $("#answer_" + answer_id.toString() + "-all-comments").html('<%=j render :partial => 'comments/comments', locals: {comments: @comments, commentable: @commentable} %>');
<% else %>
    $("#question-all-comments").html('<%=j render :partial => 'comments/comments', locals: {comments: @comments, commentable: @commentable} %>');
<% end %>

app/views/comments/destroy.js.erb
<% if @commentable.is_a?(Answer) %>
    var answer_id = <%= @commentable.id %>;
    $("#answer_" + answer_id.toString() + "-all-comments").html('<%=j render :partial => 'comments/comments', locals: {comments: @comments, commentable: @commentable} %>');
<% else %>
    $("#question-all-comments").html('<%=j render :partial => 'comments/comments', locals: {comments: @comments, commentable: @commentable} %>');
<% end %>

app/views/comments/edit.js.erb
<% if @comment.commentable.is_a?(Answer) %>
var answer_id = <%= @comment.commentable.id %>;
$("#a_" + answer_id.toString() + "-comment-form").html('<%=j render :partial => 'comments/form', locals: {comment: @comment, commentable: @comment.commentable} %>');
<% else %>
var ques_id = <%= @comment.commentable.id %>;
$("#q_" + ques_id.toString() + "-comment-form").html('<%=j render :partial => 'comments/form', locals: {comment: @comment, commentable: @comment.commentable} %>');
<% end %>

app/views/comments/update.js.erb
<% if @commentable.is_a?(Answer) %>
    var answer_id = <%= @commentable.id %>;
    $("#answer_" + answer_id.toString() + "-all-comments").html('<%=j render :partial => 'comments/comments', locals: {comments: @comments, commentable: @commentable} %>');
<% else %>
    $("#question-all-comments").html('<%=j render :partial => 'comments/comments', locals: {comments: @comments, commentable: @commentable} %>');
<% end %>