config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'dashboard' => 'dashboard#index'
    resources :users
  end

  resources :questions do
    collection do
      get :pending_questions
    end
    post :approval
    resources :answers
  end

  resources :comments, only: [:edit, :create, :update, :destroy]

  get '/upvote' => 'vote#upvote'
  get '/downvote' => 'vote#downvote'
  get '/accepted' => 'vote#accepted'

  resources :profiles, only: [:show, :edit, :update]

  get '/pages/tags' => 'pages#tags'
  get '/pages/rules' => 'pages#rules'
  get '/users' => 'pages#users'
  get 'search' => 'search#search', :as => 'search'

  devise_for :users, path_names: { sign_up: 'register' },
             controllers: {  omniauth_callbacks:  'users/omniauth_callbacks',
                             sessions:            'sessions',
                             registrations:       'registrations',
                             passwords:           'passwords'
             }

  root 'questions#index'
  get '/all_tags' => 'home#all_tags'

  resources :home do
    collection do
      post :local_switcher
    end
  end

end

app/views/shared/_avotes.html.erb
<div class="vote-actions">
  <a href="<%= upvote_path(a_id: answer.id) %>" data-remote="true">
    <i class="fa fa-chevron-up fa-3x <%= upvoted(answer) ? 'voted' : 'not-voted' %>"> </i>
  </a>

  <span>
    <div class="ans-upvote-count">+<%= answer.upvotes.count %></div>
    <div class="vote-count-separator"></div>
    <div class="ans-downvote-count">-<%= answer.downvotes.count %></div>
  </span>

  <a href="<%= downvote_path(a_id: answer.id) %>" data-remote="true">
    <i class="fa fa-chevron-down fa-3x <%= downvoted(answer) ? 'voted' : 'not-voted' %>"> </i>
  </a>

  <% if current_user == answer.question.user %>
      <a href="<%= accepted_path(a_id: answer.id) %>" data-remote="true">
        <i class="fa fa-check fa-3x <%= answer.accepted ? 'accepted' : 'not-voted' %>"> </i>
      </a>
  <% else %>
      <a href="javascript:void(0)">
        <i class="fa fa-check fa-3x <%= answer.accepted ? 'accepted' : 'hidden' %>"> </i>
      </a>
  <% end %>
</div>

app/views/shared/_dashboard_sidebar.html.erb
<div class="wrapper wrapper-content project-manager">
  <h4>Site Detail</h4>

  <table class="table small m-b-xs">
    <tbody>
    <tr>
      <td>
        Questions: <strong><%= all_questions.count %></strong>
      </td>
    </tr>
    <tr>
      <td>
        Answers: <strong><%= all_answers.count %></strong>
      </td>
    </tr>
    <tr>
      <td>
        Tags: <strong><%= all_tags.count %></strong>
      </td>
    </tr>
    </tbody>
  </table>

  <div class="advertise-zone" style="margin-bottom: 15px">
    <%= image_tag 'http://placehold.it/230x250' %>
  </div>

  <h4>Top Tags</h4>

  <% all_tags.most_used(10).each do |tag| %>
      <a class="btn btn-white btn-sm" href="<%= questions_path(t: tag.name) %>" data-no-turbolink="true">
        <i class="fa fa-tag"></i> <%= tag.name %>
      </a>
      <%#= link_to tag, questions_path(t: tag), class: 'btn btn-primary btn-xs' %>
  <% end %>

  <ul class="todo-list m-t small-list ui-sortable">
    <h5>TOP Questions</h5>
    <% top_questions(nil).each do |ques| %>
        <li>
          <a class="check-link" href="<%= question_path(ques[3]) %>" data-no-turbolink="true">
            <span class="m-l-xs"><%= ques[2] %></span>
          </a>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_detail_sidebar.html.erb
<div class="wrapper wrapper-content project-manager">
  <h4>Question description</h4>

  <table class="table small m-b-xs">
    <tbody>
    <tr>
      <td>
        Asked: <strong><%= distance_of_time_in_words(Time.now - question.created_at) %></strong>
      </td>
    </tr>
    <tr>
      <td>
        Viewed: <strong><%= question.impressionist_count %></strong>
      </td>
    </tr>
    </tbody>
  </table>

  <p class="small font-bold">
    <span><i class="fa fa-circle text-warning"></i> Top Questions</span>
  </p>
  <ul class="todo-list m-t small-list ui-sortable">
    <% top_questions(question.id).each do |ques| %>
        <li>
          <a class="check-link" href="<%= question_path(ques[3]) %>" data-no-turbolink="true">
            <span class="m-l-xs"><%= ques[2] %></span>
          </a>
        </li>
    <% end %>
  </ul>

  <div class="advertise-zone" style="margin-bottom: 15px">
    <%= image_tag 'http://placehold.it/230x250' %>
  </div>

  <h5>Related Questions</h5>
  <ul class="todo-list m-t small-list ui-sortable">
    <% related_questions(question).each do |ques| %>
        <li>
          <a class="check-link" href="<%= question_path(ques) %>" data-no-turbolink="true">
            <span class="m-l-xs"><%= ques.title %></span>
          </a>
        </li>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if data_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_model.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
        <% data_model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_qvotes.html.erb
<div class="vote-actions">
  <a href="<%= upvote_path(q_id: question.id) %>" data-remote="true">
    <i class="fa fa-chevron-up fa-4x <%= upvoted(question) ? 'voted' : 'not-voted' %>"> </i>
  </a>

  <span>
    <div class="ques-upvote-count">+<%= question.upvotes.count %></div>
    <div class="vote-count-separator"></div>
    <div class="ques-downvote-count">-<%= question.downvotes.count %></div>
  </span>

  <a href="<%= downvote_path(q_id: question.id) %>" data-remote="true">
    <i class="fa fa-chevron-down fa-4x <%= downvoted(question) ? 'voted' : 'not-voted' %>"> </i>
  </a>
</div>

app/views/shared/_site_navbar.html.erb
<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">

    <a class="navbar-minimalize minimalize-styl-2" href="<%= root_path %>"><%= t('hello') %></a>

    <%= form_tag search_path, :method => :get, class: "navbar-form-custom" do %>
        <div class="form-group">
          <%= text_field_tag :keywords, params[:keywords], placeholder: "Search for something...",  class: "form-control", id: "top-search" %>
        </div>
    <% end %>

  </div>
  <ul class="nav navbar-top-links navbar-right">
    <li>
      <%= form_tag local_switcher_home_index_path, :class => 'locale' do %>
          <%= select_tag 'locale_set', options_for_select(LANGUAGES, I18n.locale.to_s), :onchange => 'this.form.submit()' %>
      <% end %>
    </li>

    <% if current_user %>
        <li class="user-info">
           <%= render :partial => 'shared/user_info' %>
        </li>

        <li>
          <%= link_to destroy_user_session_path, :method => 'delete' do %>
              <i class="fa fa-sign-out"></i> Log out
          <% end %>
        </li>
    <% else %>
        <li>
          <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in"></i> Login
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path do %>
              <i class="fa fa-user-plus"></i> Signup
          <% end %>
        </li>
        <li>
          <%= link_to pages_rules_path do %>
              <i class="fa fa-bullhorn"></i> Rules
          <% end %>
        </li>
    <% end %>
  </ul>

</nav>

app/views/shared/_top_options_bar.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-md-4">
    <h2>IslamJanun</h2>
  </div>
  <div class="col-md-8 text-right">
    <h2 class="count-info">
      <%= link_to 'Ask Question', new_question_path, class: "btn btn-primary btn-md", 'data-no-turbolink' => true %>
      <%= link_to 'Questions', questions_path, class: "btn btn-primary btn-md"%>
      <%= link_to 'Users', users_path, class: "btn btn-primary btn-md" %>
      <%= link_to 'Tags', pages_tags_path, class: "btn btn-primary btn-md" %>
      <%= link_to 'Rules', pages_rules_path, class: "btn btn-primary btn-md" %>
      <% if current_user.present? && current_user.is_admin? %>
        <%= link_to 'Admin Panel', admin_dashboard_path, class: "btn btn-primary btn-md" %>
      <% end %>
      <% if current_user.present? && current_user.is_moderator? %>
          <span class="label label-warning"><%= pending_questions.count %></span>
          <%= link_to 'PendingQs', pending_questions_questions_path, class: "btn btn-primary btn-md" %>
      <% end %>
    </h2>
  </div>
</div>

app/views/shared/_user_info.html.erb
<%= link_to profile_path(current_user.profile) do %>
    <%= image_tag current_user.profile.photo.present? ? current_user.profile.photo_url(:thumb) : 'http://placehold.it/50x50' %>

    <span>
                <span style="margin-left: 5px"><%= current_user.profile.name %></span>
                <span><i class="fa fa-trophy text-warning"></i><%= current_user.profile.points %> </span>
              </span>
<% end %>